### ISSUE TITLE
无法调用方法。此语言模式仅支持核心类型的方法调用。 我遇到了这个问题,目前找不到解决方法

### ISSUE THREAD

**Issue by LY1806620741** [ccmywish/rbenv-for-windows#27]
```powershell
icm -sc ([scriptblock]::Create($s.Content
)) -arg "install", "cn"
无法调用方法。此语言模式仅支持核心类型的方法调用。
所在位置 行:1 字符: 1
+ icm -sc ([scriptblock]::Create($s.Content)) -arg "install", "cn"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
```

**Comment by LY1806620741** [comment]
我用了笨方法,有更高明的解决方法么

$env:RBENV_ROOT = "C:\Ruby-on-Windows"
$s = (iwr -useb "https://gitee.com/ccmywish/rbenv-for-windows/raw/main/tools/install.ps1")
$s.Content > 1.ps1
.\1.ps1 install cn
del .\1.ps1

**Comment by ccmywish** [comment]
你好 @LY1806620741 

你的 PowerShell 版本是什么？可以通过 `$PSVersionTable` 查看

**Comment by LY1806620741** [comment]
> 你好 @LY1806620741
> 
> 你的 PowerShell 版本是什么？可以通过 `$PSVersionTable` 查看

PS C:\Users\biewang\Documents> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.5576
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.5576
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by LY1806620741** [comment]
我发现在init脚本依然使用了微软定义的入侵语言，安装失败了

```powershell
Seems you have just installed rbenv, auto install MSYS2 for you
MSYS2 is must-have if you want to install gems with C extensions
Using mirror for downloading RubyInstaller-devkit(MSYS2):
Begin downloading ...
=> https://mirror.sjtu.edu.cn/github-release/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.3.0-1/rubyinstaller-devkit-3.3.0-1-x64.exe
无法调用方法。此语言模式仅支持核心类型的方法调用。
所在位置 C:\Ruby-on-Windows\rbenv\libexec\rbenv-install.ps1:105 字符: 5
+     $wreq = [net.webrequest]::create($reqUrl)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) []，ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage

```

**Comment by ccmywish** [comment]
我试了下，版本 `5.1.2262` 是可以工作的。所以应该是你的PowerShell版本过低了。
这个调用方法都是参考 `scoop` 项目这儿来的，这些方法也是他们下载时用的逻辑，所以如果这里调用不了，你可能 `scoop` 运行也有问题。所以建议您更新为最新的 Pwsh https://learn.microsoft.com/zh-cn/powershell/

```PowerShell
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by LY1806620741** [comment]
> 我试了下，版本 `5.1.2262` 是可以工作的。所以应该是您的PowerShell版本过低了。 这个调用方法参考自 `scoop` 项目，这些方法也是他们下载时使用的，所以如果这里调用不了，您可能运行 `scoop` 也会有问题。因此建议您更新为最新的 Pwsh https://learn.microsoft.com/zh-cn/powershell/
> 
> ```powershell
> ❯ $PSVersionTable
> 
> Name                           Value
> ----                           -----
> PSVersion                      5.1.22621.2506
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.22621.2506
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> ```

我觉得问题的本质是
`$ExecutionContext.SessionState.LanguageMo
de`属性是`ConstrainedLanguage`此时被拦截，但我找不到方法切换为`FullLanguage`应该不是版本问题

**Comment by ccmywish** [comment]
@LY1806620741 了解了。我觉得最省事的解决方法就是更新。但您提出的这个点值得进一步考虑，我有空将会研究一下。此 issue 将保持开启。

**Comment by LY1806620741** [comment]
可能有用的文档

https://learn.microsoft.com/zh-cn/windows/security/application-security/application-control/windows-defender-application-control/wdac

https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.4

**Comment by LY1806620741** [comment]
已解决问题
![image](https://github.com/ccmywish/rbenv-for-windows/assets/25952861/54382135-8090-4c56-ac9d-76b1ebb9f94e)
由4改成8
![image](https://github.com/ccmywish/rbenv-for-windows/assets/25952861/0230c231-da1f-4f03-9a77-1c5c50dc5fa2)

**Comment by LY1806620741** [comment]
this is a tips for People who have never studied Chinese.

key sentences: PowerShell、Only core types are supported in this language mode.

If you want to set the default language mode of powershell and cannot find Internet information, you can try this method. Modify the windows system environment variable `__PSLockdownPolicy` and restart, this works for me. Edit this article to provide effective solutions for the Internet, maybe you found it from a search engine.

8: FullLanguage
4:ConstrainedLanguage

**Comment by ccmywish** [comment]
Good solution, thanks for discovering and sharing it! @LY1806620741
