### ISSUE TITLE
no correct curl.exe  default

### ISSUE THREAD

**Issue by SKOLIA0** [ccmywish/rbenv-for-windows#30]
PS C:\Users\pc-win> iwr -useb "https://github.com/ccmywish/rbenv-for-windows/raw/main/tools/install.ps1" | iex

    Каталог: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        24.08.2024     15:50                Ruby-on-Windows
Cloning into 'rbenv'...
remote: Enumerating objects: 1575, done.
remote: Counting objects: 100% (408/408), done.
remote: Compressing objects: 100% (181/181), done.
remote: Total 1575 (delta 235), reused 376 (delta 212), pack-reused 1167 (from 1)
Receiving objects: 100% (1575/1575), 445.50 KiB | 9.00 KiB/s, done.
Resolving deltas: 100% (1011/1011), done.
rbenv: Downloading pre-compiled binaries from GitHub... curl.exe : Имя "curl.exe" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьт
е правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:37 знак:5
+     curl.exe -sSL "$repo/releases/download/$tag/ruby.exe" -o "$env:RB ...
+     ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (curl.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

curl.exe : Имя "curl.exe" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьт
е правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:39 знак:5
+     curl.exe -sSL "$repo/releases/download/$tag/rbenv-exec.exe" -o "$ ...
+     ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (curl.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Finished
rbenv: Installation Complete!

PS C:\Users\pc-win>
>> curl --version
curl : Невозможно разрешить удаленное имя: '--version'
строка:2 знак:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\pc-win> C:\Windows\System32\curl.exe --version
>>
curl 8.7.1 (Windows) libcurl/8.7.1 Schannel zlib/1.3 WinIDN
Release-Date: 2024-03-27
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
PS C:\Users\pc-win>
>> curl --version
curl : Невозможно разрешить удаленное имя: '--version'
строка:2 знак:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\pc-win> curl --version
curl : Невозможно разрешить удаленное имя: '--version'
строка:1 знак:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\pc-win> Set-Alias curl C:\Windows\System32\curl.exe
>>
Set-Alias : Не удается удалить параметр AllScope из псевдонима "curl".
строка:1 знак:1
+ Set-Alias curl C:\Windows\System32\curl.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (curl:String) [Set-Alias], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : AliasAllScopeOptionCannotBeRemoved,Microsoft.PowerShell.Commands.SetAliasCommand

PS C:\Users\pc-win> notepad $PROFILE
>>
PS C:\Users\pc-win>
>> New-Item -Path $PROFILE -ItemType File -Force

    Каталог: C:\Users\pc-win\Documents\WindowsPowerShell

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        24.08.2024     15:55              0 Microsoft.PowerShell_profile.ps1

PS C:\Users\pc-win>
>> notepad $PROFILE
PS C:\Users\pc-win>
>> curl --version
curl : Невозможно разрешить удаленное имя: '--version'
строка:2 знак:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\pc-win> notepad $PROFILE
>>
PS C:\Users\pc-win> curl --version
>>
curl : Невозможно разрешить удаленное имя: '--version'
строка:1 знак:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\pc-win>
>> Get-Alias curl

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           curl -> Invoke-WebRequest

PS C:\Users\pc-win>
>> Remove-Item Alias:curl -Force
PS C:\Users\pc-win>
>> Set-Alias curl C:\Windows\System32\curl.exe
PS C:\Users\pc-win>
>> curl --version
curl 8.7.1 (Windows) libcurl/8.7.1 Schannel zlib/1.3 WinIDN
Release-Date: 2024-03-27
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets

**Comment by SKOLIA0** [comment]
PS C:\Users\pc-win> curl --version
>>
curl : Невозможно разрешить удаленное имя: '--version'
строка:1 знак:1
+ curl --version
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\Users\pc-win>
>> Get-Alias curl

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           curl -> Invoke-WebRequest


PS C:\Users\pc-win>
>> Remove-Item Alias:curl -Force
PS C:\Users\pc-win>
>> Set-Alias curl C:\Windows\System32\curl.exe
PS C:\Users\pc-win>
>> curl --version
curl 8.7.1 (Windows) libcurl/8.7.1 Schannel zlib/1.3 WinIDN
Release-Date: 2024-03-27
Protocols: dict file ftp ftps http https imap imaps ipfs ipns mqtt pop3 pop3s smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM SPNEGO SSL SSPI threadsafe Unicode UnixSockets
PS C:\Users\pc-win>

**Comment by ccmywish** [comment]
Hello @SKOLIA0 

I know in PowerShell v5.1, `curl` is an alias to `Invoke-Webrequest`. So I explicitly use `curl.exe` to invoke the real `curl.exe` program.

So please first install `curl.exe` via 
1. `$ scoop install curl` 
2. `$ choco install curl`
3. Or download it into your PATH

to make `rbenv` installation script find it.


https://github.com/ccmywish/rbenv-for-windows/blob/main/tools/install.ps1#L37-L39

**Comment by SKOLIA0** [comment]
Hi, @ccmywish. Thank you for the response. I tried a similar approach (listing the commands with explanations):

    Go to the release page of rbenv-for-windows via your browser.
    In the "Assets" section, download the following two files:
        ruby.exe
        rbenv-exec.exe
    Save these files in the following directories:
        ruby.exe in C:\Ruby-on-Windows\rbenv\bin\
        rbenv-exec.exe in C:\Ruby-on-Windows\rbenv\libexec\

I did this and executed the following commands:

powershell

PS C:\Users\pc-win>
>> & "$env:RBENV_ROOT\rbenv\bin\rbenv.ps1" init

powershell

PS C:\Users\pc-win> rbenv update

I got the following output:

text

Already up to date.
C:\Ruby-on-Windows\rbenv\tools\install.ps1:17 sign:41
+     $welcome = "rbenv: д»ЋGiteeдё‹иЅЅйў„зј–иЇ‘дєЊиї›е€¶ж–‡д»¶... "
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token "зј–иЇ‘дєЊиї›е€¶ж–‡д»¶... "
    $goodbye = "з»“жќџ"
    $err_msg = 'rbenv' in the expression or operator.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

Then I changed the console encoding with the following command:

powershell

PS C:\Users\pc-win> [Console]::OutputEncoding = [System.Text.Encoding]::UTF8

And re-ran the rbenv initialization:

powershell

PS C:\Users\pc-win> & "$env:RBENV_ROOT\rbenv\bin\rbenv.ps1" init

Finally, I checked the rbenv version:

powershell

PS C:\Users\pc-win> rbenv --version
rbenv v1.5.0

In the end, I manually copied the release asset files and placed them in the required folders.

**Comment by SKOLIA0** [comment]
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
The first version may have been the problem

**Comment by ccmywish** [comment]
Yes, you are right.

The `rbenv update` command will
1. `git pull`
2. Always download the binaries to replace the local ones regardless the versions.

The step 2 is also done via the installer script: 
https://github.com/ccmywish/rbenv-for-windows/blob/main/tools/install.ps1#L37-L39

So it still needs `curl.exe`.....

**Comment by ccmywish** [comment]
Maybe I figured out what was wrong.

See: https://github.com/ccmywish/rbenv-for-windows/blob/main/tools/install.ps1#L15-L29

The file `install.ps1` indeed is encoded in UTF-8, but it includes Chinese characters.

Maybe in your environment, `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` will identify this file as Russian encodings which make the PowerShell interpreter complain.

**Comment by ccmywish** [comment]
I've removed the Chinese characters.

Please use `rbenv update`.

If the first time `rbenv update` meets an error, just run it twice.

**Comment by SKOLIA0** [comment]
PowerShell 7.4.5
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv update   
fatal: cannot change to '\rbenv': No such file or directory
&: C:\Ruby-on-Windows\rbenv\libexec\rbenv-update.ps1:20
Line |
  20 |          & "$env:RBENV_ROOT\rbenv\tools\install.ps1" update
     |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '\rbenv\tools\install.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
     | try again.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv --version
rbenv v1.5.0
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2>

**Comment by SKOLIA0** [comment]
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv --update
rbenv: '--update' isn't a rbenv command. See 'rbenv help'.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv version
&: C:\Ruby-on-Windows\rbenv\lib\version.ps1:101
Line |
 101 |      $msg = & $env:RBENV_ROOT\rbenv\bin\ruby.exe -v
     |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '\rbenv\bin\ruby.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try     
     | again.

PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv --version
rbenv v1.5.0
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2>



PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv help     
Usage: rbenv <command> [<args>]
Some useful commands are:

commands   List all available rbenv commands
global     Set or show the global Ruby version
help       Show help for a command
install    Install a Ruby version using RubyInstaller2
local      Set or show the local application-specific Ruby version
rehash     Rehash rbenv shims (run this after installing gems)
root       Display the root directory where versions and shims are kept
shell      Sets a shell-specific Ruby version
uninstall  Uninstall a specific Ruby version
update     Update rbenv or MSYS2
version    Show the current Ruby version and its origin
versions   List installed Ruby versions
whence     List all Ruby versions that contain the given executable
which      Display the full path to an executable

Type 'rbenv help <command>' to get help for a specific command.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv --help   
Usage: rbenv <command> [<args>]
Some useful commands are:

commands   List all available rbenv commands
global     Set or show the global Ruby version
help       Show help for a command
install    Install a Ruby version using RubyInstaller2
local      Set or show the local application-specific Ruby version
rehash     Rehash rbenv shims (run this after installing gems)
root       Display the root directory where versions and shims are kept
shell      Sets a shell-specific Ruby version
uninstall  Uninstall a specific Ruby version
update     Update rbenv or MSYS2
version    Show the current Ruby version and its origin
versions   List installed Ruby versions
whence     List all Ruby versions that contain the given executable
which      Display the full path to an executable

Type 'rbenv help <command>' to get help for a specific command.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2>

**Comment by SKOLIA0** [comment]
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv install 2.7.8 -devkit
version < '3.1.0-1' need mingw64 toolchain (Not compatible with our shared MSYS2's ucrt64 toolchain)
Only full version can make you install a gem with C extensions

  1. Lite version 2.7.8-1 (less than 15MB) [Default]
  2. Full version 2.7.8-1-with-devkit? (at least 130MB)

Which one?: 2
Begin downloading ...
=> https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.7.8-1/rubyinstaller-devkit-2.7.8-1-x64.exe
rubyinstaller-devkit-2.7.8-1-x64.exe (126,3 MB) [=========================================================================================================================================================================] 100%
Installing rubyinstaller-devkit-2.7.8-1-x64.exe ...
&: C:\Ruby-on-Windows\rbenv\libexec\rbenv-rehash.ps1:17
Line |
  17 |      & "$env:RBENV_ROOT\rbenv\libexec\rbenv-exec.exe" rehash-version $ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '\rbenv\libexec\rbenv-exec.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct   
     | and try again.
rbenv: Remove version 2.7.8-1 registry info 
rbenv: Version '2.7.8-1' with devkit was installed successfully!
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv local 2.7.8          
rbenv: version 2.7.8 not installed
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv local 2.7.8-1
rbenv: version 2.7.8-1 not installed
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv list         
rbenv: 'list' isn't a rbenv command. See 'rbenv help'.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv help                 
Usage: rbenv <command> [<args>]
Some useful commands are:

commands   List all available rbenv commands
global     Set or show the global Ruby version
help       Show help for a command
install    Install a Ruby version using RubyInstaller2
local      Set or show the local application-specific Ruby version
rehash     Rehash rbenv shims (run this after installing gems)
root       Display the root directory where versions and shims are kept
shell      Sets a shell-specific Ruby version
uninstall  Uninstall a specific Ruby version
update     Update rbenv or MSYS2
version    Show the current Ruby version and its origin
versions   List installed Ruby versions
whence     List all Ruby versions that contain the given executable
which      Display the full path to an executable

Type 'rbenv help <command>' to get help for a specific command.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv versions
rbenv: No Ruby installed on your system
       Try use rbenv install <version>
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2> rbenv rehash  
&: C:\Ruby-on-Windows\rbenv\lib\version.ps1:101
Line |
 101 |      $msg = & $env:RBENV_ROOT\rbenv\bin\ruby.exe -v
     |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '\rbenv\bin\ruby.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try     
     | again.
&: C:\Ruby-on-Windows\rbenv\libexec\rbenv-rehash.ps1:17
Line |
  17 |      & "$env:RBENV_ROOT\rbenv\libexec\rbenv-exec.exe" rehash-version $ …
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term '\rbenv\libexec\rbenv-exec.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct   
     | and try again.
PS C:\Users\pc-win\RubymineProjects\redmine-5.0.2>

:-(

**Comment by ccmywish** [comment]
I think you make it too complicated.

There is NO NEED to run any other command or script!

Just ensure the installation, and then run `rbenv update`.

**Comment by ccmywish** [comment]
Please delete the all rbenv directories, and now begin to install from the start.

1. On your terminal, run this:
```
$env:RBENV_ROOT = "C:\Ruby-on-Windows"
iwr -useb "https://github.com/ccmywish/rbenv-for-windows/raw/main/tools/install.ps1" | iex
```

2. In your `$profile` file, add these lines:
```
$env:RBENV_ROOT = "C:\Ruby-on-Windows"
& "$env:RBENV_ROOT\rbenv\bin\rbenv.ps1" init
```

3. now, the `rbenv` is installed successfully! No any other step.

**Comment by ccmywish** [comment]
The successfully installed `$env:RBENV_ROOT` dir will be like this:

![image](https://github.com/user-attachments/assets/81128ec4-0944-4bc4-b53c-4cf1a7ca124f)

**Comment by SKOLIA0** [comment]
PowerShell 7.4.5
PS C:\Users\pc-win> $env:RBENV_ROOT = "C:\Ruby-on-Windows"
PS C:\Users\pc-win> iwr -useb "https://github.com/ccmywish/rbenv-for-windows/raw/main/tools/install.ps1" | iex

    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          24.08.2024    20:20                Ruby-on-Windows
Cloning into 'rbenv'...
remote: Enumerating objects: 1583, done.
remote: Counting objects: 100% (416/416), done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 1583 (delta 241), reused 381 (delta 215), pack-reused 1167 (from 1)
Receiving objects: 100% (1583/1583), 446.55 KiB | 2.25 MiB/s, done.
Resolving deltas: 100% (1017/1017), done.
rbenv: Downloading pre-compiled binaries from GitHub... curl.exe:
Line |
  35 |      curl.exe -sSL "$repo/releases/download/$tag/ruby.exe" -o "$env:RB …
     |      ~~~~~~~~
     | The term 'curl.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
curl.exe:
Line |
  37 |      curl.exe -sSL "$repo/releases/download/$tag/rbenv-exec.exe" -o "$ …
     |      ~~~~~~~~
     | The term 'curl.exe' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Finished
rbenv: Installation complete!



PS C:\Users\pc-win>
![image](https://github.com/user-attachments/assets/541f0e5d-d2ee-477f-b709-589850d02890)

![image](https://github.com/user-attachments/assets/faf69eef-f8ab-40bb-8a91-7bf8d725b41c)
copy 2 file

**Comment by ccmywish** [comment]
I think your system lack `curl.exe`, please download and install it first!

https://curl.se/download.html#Win64

**Comment by ccmywish** [comment]
After you make sure `curl.exe` is available, I think you will succeed just by a single step: `rbenv update`.

**Comment by SKOLIA0** [comment]
> I think your system lack `curl.exe`, please download and install it first!
> 
> https://curl.se/download.html#Win64
> 
> Make sure you can run `curl --version` from the command line.
> 
> ![image](https://private-user-images.githubusercontent.com/63459097/361162494-acb3a9fc-88b2-4590-96ff-8c152f6199a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MjQ3MzEsIm5iZiI6MTcyNDUyNDQzMSwicGF0aCI6Ii82MzQ1OTA5Ny8zNjExNjI0OTQtYWNiM2E5ZmMtODhiMi00NTkwLTk2ZmYtOGMxNTJmNjE5OWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE4MzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYWYwMTUwZDhkMTdjZWVmNDU1OTRiYjMwMDMzOWI2NTNhYWQ1ODQ0ZTIzZDk5ZTQxNzQyZjFiM2VmZDUxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rpLAixUdXmonaUdVc2UBeNKzTlxHWktMByQrHSE1C4Y)

you update README.md  =)

**Comment by SKOLIA0** [comment]
I think your system lack curl.exe, please download and install it first!

```https://curl.se/download.html#Win64```

Make sure you can run ```curl --version``` from the command line.

if install https://scoop.sh/   curl
Close all the sessions of PowerShell! Restart a new PowerShell, then you will find everything works

and 

Close all the sessions of PowerShell! Restart a new PowerShell, then you will find everything works

Make sure you can run ```curl --version``` from the command line.


you update README.md =)
Please delete all the rbenv directories, and now begin to reinstall from the start.

On your terminal, run this:
```$env:RBENV_ROOT = "C:\Ruby-on-Windows"
iwr -useb "https://github.com/ccmywish/rbenv-for-windows/raw/main/tools/install.ps1" | iex```
In your $profile file, add these lines:
```

```
```$env:RBENV_ROOT = "C:\Ruby-on-Windows"
& "$env:RBENV_ROOT\rbenv\bin\rbenv.ps1" init```
now, the rbenv is installed successfully! No any other step.

Close all the sessions of PowerShell! Restart a new PowerShell, then you will find everything works

**Comment by SKOLIA0** [comment]
Большое спасибо
![image](https://github.com/user-attachments/assets/13c4c6bb-1d08-4af8-b411-67b57836b78d)
非常感谢

**Comment by ccmywish** [comment]
1. Пожалуйста
2. 不用谢
3. You're welcome

Very happy to see you solved the problem! Congratulations!

`curl` is a very famous tool, and Windows 11 has already shipped it by default, so I don't mention it in the README.

![image](https://github.com/user-attachments/assets/7c06d07c-676d-4a91-9234-9c8533bb67ba)

**Comment by SKOLIA0** [comment]
https://github.com/SKOLIA0/rbenv-for-windows/blob/main/README_RU.md

You have a lot of questions from people with Russian names, I have made a fresh starting instruction for them.

**Comment by ccmywish** [comment]
👍 I've added your instruction article in README's installation section.

See: https://github.com/ccmywish/rbenv-for-windows#install
