### ISSUE TITLE
Not working on Windows 11

### ISSUE THREAD

**Issue by SamarthaKV29** [ccmywish/rbenv-for-windows#8]
It says starting download and then just fails. Even though I am able to download the file manually from the link

**Comment by ccmywish** [comment]
Hi @SamarthaKV29, 

Could you provide a screenshot? 

And could you provide the `$PSVersionTable` to show your PowerShell version?

**Comment by ccmywish** [comment]
Hi @SamarthaKV29 

Be sure to not add the Chinese mirror site in your config! See #7

**Comment by ccmywish** [comment]
I will close this issue. If there are still any questions, please feel free to come back and ask.
